-- 001: база знаний для RAG — таблица knowledge_chunks с embeddings в pgvector.
-- Выполнить один раз в Supabase: Dashboard → SQL Editor → вставить файл целиком → Run (или `supabase db push`).
-- Тот же SQL задокументирован в docs/001_create_knowledge_chunks_table.sql; держать файлы одинаковыми.
--
-- Строки пишет только `npm run ingest` (scripts/ingest.ts): 1 чанк = 1 секция «## …» из knowledge/*.md.
-- Ингест очищает таблицу и заливает её заново, поэтому данные здесь — производные от knowledge/, не источник правды.

create extension if not exists vector;

create table if not exists public.knowledge_chunks (
  id        bigint generated by default as identity primary key,
  file      text not null,          -- имя файла в knowledge/, например recipes.md
  heading   text not null,          -- текст заголовка секции «## …» без решёток
  content   text not null,          -- тело секции без строки заголовка
  -- 1536 — размерность text-embedding-3-small. Другая модель с другой размерностью = новая миграция.
  embedding vector(1536) not null,
  unique (file, heading)
);

-- Поиск в src/rag/retriever.ts: order by embedding <=> query (косинусное расстояние), поэтому vector_cosine_ops.
create index if not exists knowledge_chunks_embedding_idx
  on public.knowledge_chunks using hnsw (embedding vector_cosine_ops);

-- Приложение ходит в БД напрямую по SUPABASE_DB_URL (роль-владелец обходит RLS). RLS без политик закрывает
-- таблицу от публичного REST API Supabase (роли anon/authenticated).
alter table public.knowledge_chunks enable row level security;
